server:
    port: 8088

spring:
    # Maria DB
    datasource:
        driver-class-name: org.mariadb.jdbc.Driver
        url: jdbc:mariadb://maria-container:6033/devops
        username: root
        password: 123456789

        # # Mybatis 설정
# 해당 경로에 있는 *Mapper.xml 파일과 *Mapper.java를 연결

# Mapper XML 파일 경로 (classpath 기준 또는 절대 경로)
mybatis:
    mapper-locations: /mappers/**/*Mapper.xml
# MyBatis 설정 파일 위치 (typeAlias 등 설정 포함)
# 입력 및 반환에 대한 타입 설정하는 파일
    config-location: classpath:mybatis-config.xml

# # jpa
# # spring:
# #     jpa:
# #         properties:
# #             hibernate:
# #                 dialect: org.hibernate.dialect.MariaDBDialect
# #                 show_sql: true
# #                 format_sql: true
# #                 use_sql_comments: true
# # # auto type : create, none, update
# #         hibernate:
# #             ddl-auto: none
# #